# Server variables
num_clients : 10
production_mode : False
strategy : FedAvg
metrics_aggregation: weighted_average
features : maggic
num_rounds : 1

min_fit_clients : 1
min_evaluate_clients : 1
min_available_clients : 1