# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en /app
WORKDIR .

# Copia el script de Python al contenedor
COPY script.py .

# Ejecuta el script cuando se inicie el contenedor
CMD ["python", "script.py"]
